
#define SEGMENT_NBR_0	0x3F
#define SEGMENT_NBR_1	0x06
#define SEGMENT_NBR_2	0x5B
#define SEGMENT_NBR_3	0x4F
#define SEGMENT_NBR_4	0x66
#define SEGMENT_NBR_5	0x6D
#define SEGMENT_NBR_6	0x7D
#define SEGMENT_NBR_7	0x07
#define SEGMENT_NBR_8	0x7F
#define SEGMENT_NBR_9	0x6F
#define SEGMENT_NBR_A	0x77
#define SEGMENT_NBR_B	0x7C
#define SEGMENT_NBR_C	0x39
#define SEGMENT_NBR_D	0x5E
#define SEGMENT_NBR_E	0x79
#define SEGMENT_NBR_F	0x71




#define SEGMENT_LETTER_A 0x77
#define SEGMENT_LETTER_B 0x7C
#define SEGMENT_LETTER_C 0x39
#define SEGMENT_LETTER_D 0x5E
#define SEGMENT_LETTER_E 0x79
#define SEGMENT_LETTER_F 0x71
#define SEGMENT_LETTER_G 0x6F
#define SEGMENT_LETTER_H 0x76
#define SEGMENT_LETTER_I 0x30
#define SEGMENT_LETTER_J 0x1E
#define SEGMENT_LETTER_K 0x75
#define SEGMENT_LETTER_L 0x38
#define SEGMENT_LETTER_M 0x15
#define SEGMENT_LETTER_N 0x54
#define SEGMENT_LETTER_O 0x5C
#define SEGMENT_LETTER_P 0x73
#define SEGMENT_LETTER_Q 0x67
#define SEGMENT_LETTER_R 0x50
#define SEGMENT_LETTER_S 0x6D
#define SEGMENT_LETTER_T 0x78
#define SEGMENT_LETTER_U 0x3E
#define SEGMENT_LETTER_V 0x1C
#define SEGMENT_LETTER_W 0x2A
#define SEGMENT_LETTER_X 0x76
#define SEGMENT_LETTER_Y 0x6E
#define SEGMENT_LETTER_Z 0x5B

